### ISSUE TITLE
Issue with vlan

### ISSUE THREAD

**Issue by subrnath** [Intel-Corp/sriov-cni#11]
i am using this plugin for Kubernetes POD having DPDK based application. There are 10 virtual functions defined for the physical NIC. For the first POD,  three virtual functions are allocated. First one is without any vlan tagging and second & third ones are defined with vlan fields.  POD came up fine and we can see three virtual functions are bind by uio_igb driver. "ip link show" commands show VF-0 without any VLAN, VF-1 with vlan 1925 and VF-2 with vlan 1926. ( Here vlan 1925 and vlan 1926 as defined. )

Now we start the second POD. Two virtual function are allocated for that. Both will be with vlan. SRIOV plugin to find out next available virtual function which is VF-3 and VF-4. But we can see its allocates VF-0 for this second POD also and due to this connectivity of the first POD is broken.

This problem seems to be with untagged vlan used for first POD. If no untagged vlan used, this works fine ie for the second POD, VF-3 and VF-4 is assigned,

**Comment by rkamudhan** [comment]
@subrnath as you explained `we can see its allocates VF-0 for this second POD also and due to this connectivity of the first POD is broken`

Is this case in your deployment ? I don't think it will happen in our current implementation. Could you please confirm it ? because once the VF are bonded to uio_igb driver, they are no longer in kernel space. It is not possible for the SRIOV CNI to find VF0 the next available virtual function. Please correct me on this.

**Comment by subrnath** [comment]
With Kubernetes v1.10.2, this issue is not seen. Hence closing this ticket.
